[goldmark]
[goldmark.extensions]
[goldmark.extensions.cjk]
eastAsianLineBreaks = true
enable = true
escapedSpace = true

[highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
lineNos = true
tabWidth = 2
style = 'catppuccin-frappe'
