[goldmark]
[goldmark.extensions]
[goldmark.extensions.cjk]
eastAsianLineBreaks = true
enable = true
escapedSpace = true
[goldmark.renderer]
unsafe = true

[highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
hl_inline = true
lineNos = true
style = 'catppuccin-frappe'
tabWidth = 2
