baseurl: 'https://warashi.dev/'
theme: m10c
languageCode: ja-JP
defaultContentLanguage: ja
title: 404 やる気 Not Found
copyright: © 2019 Copyright warashi
canonifyurls: true
enableEmoji: true
hasCJKLanguage: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula

taxonomies:
  tag: tags

permalinks:
  post: /post/:year/:month/:day/:filename/

imaging:
  quality: 99

params:
  author: ざしきわらし
  avatar: images/tisza.png
  description: ざしきわらしがいろいろ書いている場所です
  menu_item_separator: '<br />'
  social:
    - icon: github
      name: Warashi
      url: https://github.com/Warashi
    - icon: twitter
      name: '@warashi___'
      url: https://twitter.com/warashi___

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: about Warashi
      url: /about/
      weight: 2
    - name: Blog
      url: /post/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5
