baseurl: 'https://warashi.github.io/'
theme: cupper-hugo-theme
languageCode: ja-JP
defaultContentLanguage: ja
title: 404 やる気 Not Found
copyright: © 2019 Copyright warashi
canonifyurls: true
enableEmoji: true
hasCJKLanguage: true
blackfriday:
  hrefTargetBlank: true
  nofollowLinks: true
  noreferrerLinks: true

taxonomies:
  tag: tags

permalinks:
  post: /post/:year/:month/:day/:filename/

imaging:
  quality: 99

params:
  dateFormat: '2006/01/02'

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5
