theme="amp"
languageCode = "ja-JP"
baseurl = "https://warashi.github.io"
title = "やる気 Not Found"
paginate = 10
copyright = "© 2016 Copyright warashi"
canonifyurls = true
enableEmoji = true
hasCJKLanguage = true
# googleAnalytics = "Your Tracking Id" # optional

# optional
[[menu.header]]
  name = "Tag"
  weight = 1
  url = "/tags/"
[[menu.header]]
  name = "Category"
  weight = 2
  url = "/categories/"

# optional
[social]
  twitter = "warashi___"
  github = "Warashi"
  # facebook = "Your facebook Name"
  # gplus = "Your Google+ profile name"
  # linkedin = "Your LinkedIn Name"
