version: 2

default: &default
  docker:
    - image: 6warashi9/dockerfile-for-hugo
  working_directory: ~/project
jobs:
  build:
    <<: *default
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "git submodule sync"
          command: git submodule update --init --recursive
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
      - persist_to_workspace:
          root: ~/project/public
          paths: 
            - ./

  deploy:
    <<: *default
    steps:
      - add_ssh_keys
      - attach_workspace:
          at: ~/public
      - run:
          name: "init netrc"
          command: |
            echo machine github.com >> ${HOME}/.netrc
            echo login ${GITHUB_USER} >> ${HOME}/.netrc
            echo password ${GITHUB_TOKEN} >> ${HOME}/.netrc
      - deploy:
          name: "deploy"
          command: |
            git config --global user.email '6warashi9@gmail.com'
            git config --global user.name 'CircleCI'
            git clone -b master 'https://github.com/Warashi/warashi.github.io.git' ~/repository
            cd ~/repository
            git checkout -b update/${CIRCLE_SHA1}
            rsync -va --delete --exclude '.git' --exclude '.circleci' ~/public/ ~/repository/
            git add -A
            git commit -m "CircleCI update ${CIRCLE_SHA1}"
            hub pull-request -p -b master --no-edit

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
