version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.21
    working_directory: ~/project
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: "git config"
          command: |
            git config --global user.email '6warashi9@gmail.com'
            git config --global user.name 'CircleCI'
      - run:
          name: "submodule sync"
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: "checkout master"
          command: cd public && git checkout master && git pull
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/src/
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "source" ]; then
              cd public && git add -A
              cd public && git commit -m 'CircleCI update'
              cd public && git push
            fi
