version: 2
jobs:
  build:
    docker:
      - image: 6warashi9/docker-alpine-hugo-git-ssh-rsync
    working_directory: ~/project
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: "git submodule sync"
          command: git submodule update --init --recursive
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
      - deploy:
          name: "deploy"
          command: |
            if [ "${CIRCLE_BRANCH}" == "source" ]; then
              git config --global user.email '6warashi9@gmail.com'
              git config --global user.name 'CircleCI'
              git clone 'git@github.com:Warashi/warashi.github.io' ~/public
              cd ~/public
              git checkout master
              rsync -va --delete --exclude '.git' ~/project/public/ ~/public/
              git add -A
              git commit -m 'CircleCI update'
              git push
            fi
