name: "Build and PR"
on:
  push:
    branches:
      - main

jobs:
  build_and_pr:
    name: "Build and make PR"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true
      - name: Build
        run: hugo --destination "${DESTINATION}"
        env:
          DESTINATION: ${{ github.workspace }}/docs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.2
        with:
          delete-branch: true
          branch-suffix: short-commit-hash
          reviewers: ${{ github.actor }}
