name: "Build and PR"
on:
  push:
    branches:
      - source
jobs:
  build_and_pr:
    name: "Build and make PR"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@master
        with:
          submodules: true
      - name: "Build and make PR"
        uses: Warashi/warashi.github.io@action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
